DIRECTORY="src/main/generated/com/github/vmironov/jetpack/arguments"
FILE="ArgumentsGeneratedBindings.kt"
TARGET="${DIRECTORY}/${FILE}"

rm -rf $DIRECTORY
mkdir -p $DIRECTORY
touch $TARGET

println() {
  echo "$1" >> $TARGET
}

import() {
  println "import $1"
}

println "// Code generated by ./jetpack-bindings-arguments/generate.sh"
println "package com.github.vmironov.jetpack.arguments"
println

import "android.os.Bundle"
import "android.os.Parcelable"
import "java.io.Serializable"
import "kotlin.properties.ReadOnlyProperty"

generate() {
  println ""
  println "public fun Any.bind${1}Argument(name: String? = null, default: ${1}? = null): ReadOnlyProperty<Any, ${1}> = ArgumentsVal(this, name, default) { name, bundle ->"
  println "  if (bundle.containsKey(name)) {"
  println "    bundle.get${1}(name)"
  println "  } else {"
  println "    null"
  println "  }"
  println "}"

  println ""
  println "public fun Any.bindOptional${1}Argument(name: String? = null, default: ${1}? = null): ReadOnlyProperty<Any, ${1}?> = OptionalArgumentsVal(this, name, default) { name, bundle ->"
  println "  if (bundle.containsKey(name)) {"
  println "    bundle.get${1}(name)"
  println "  } else {"
  println "    null"
  println "  }"
  println "}"
}

generate "Boolean"
generate "Double"
generate "Int"
generate "Long"
generate "String"
generate "Bundle"
generate "Byte"
generate "Char"
generate "CharSequence"
generate "Float"
generate "Parcelable"
generate "Serializable"
generate "Short"
